### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by tharuneshwar-s** [ShirleyMaxx/VirtualMarker#24]
Hi community,

Ubuntu - 22.0
GTX - 1650
RAM - 16GB
VRAM - 4GB

```
sh command/simple3dmesh_infer/baseline.sh
```

### **output**

![Screenshot from 2024-02-14 23-18-39](https://github.com/ShirleyMaxx/VirtualMarker/assets/84437531/da94d734-a77e-4331-983f-57f5a89f29d2)

How to resolve this error??

**Comment by ShirleyMaxx** [comment]
Hi, this is because the memory of RTX-1650 is relatively small. We tested on a 16GB V100. You can try running it on a GPU with a larger memory capacity, or reduce the batch size during inference via [command line argument](https://github.com/ShirleyMaxx/VirtualMarker/blob/master/main/inference.py#L49).
